//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarukSahin.DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server_Info
    {
        public string key_str { get; set; }
        public string value_str { get; set; }
    }
}
